[[rewrites]]
  from = "/help/*"
  to = "https://chatbase.co/J9jzeWbLBTD_BrL26uPn-/help/:splat"
  status = 200

[[rewrites]]
  from = "/help"
  to = "https://chatbase.co/J9jzeWbLBTD_BrL26uPn-/help"
  status = 200
