# netlify.toml
# Chatbase Help Page proxy

# Root request -> Chatbase Help page
[[redirects]]
  from = "/"
  to = "https://www.chatbase.co/J9jzeWbLBTD_BrL26uPn-/help"
  status = 200
  force = true

# All other requests (including assets) go directly to Chatbase
[[redirects]]
  from = "/*"
  to = "https://www.chatbase.co/J9jzeWbLBTD_BrL26uPn-/help/:splat"
  status = 200
  force = true
