# netlify.toml
# Correct setup for Chatbase Help page proxy (avoids redirect loops)

[[rewrites]]
  from = "/help/*"
  to = "https://www.chatbase.co/J9jzeWbLBTD_BrL26uPn-/help/:splat"
  status = 200

[[rewrites]]
  from = "/help"
  to = "https://www.chatbase.co/J9jzeWbLBTD_BrL26uPn-/help"
  status = 200
