# netlify.toml

# Send "/" to the Chatbase Help page
[[redirects]]
  from = "/"
  to   = "https://www.chatbase.co/J9jzeWbLBTD_BrL26uPn-/help"
  status = 200
  force = true

# Proxy all assets and deep links
[[redirects]]
  from = "/*"
  to   = "https://www.chatbase.co/J9jzeWbLBTD_BrL26uPn-/help/:splat"
  status = 200
  force = true

